In [1]:
import pandas as pd
import re

In [2]:
df = pd.read_csv("data/DataAnalyst.csv", index_col = 0)
df

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True
1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1
2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1
3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1
4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2248,RQS - IHHA - 201900004460 -1q Data Security An...,$78K-$104K (Glassdoor est.),Maintains systems to protect data from unautho...,2.5,"Avacend, Inc.\n2.5","Denver, CO","Alpharetta, GA",51 to 200 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,Unknown / Non-Applicable,-1,-1
2249,Senior Data Analyst (Corporate Audit),$78K-$104K (Glassdoor est.),Position:\nSenior Data Analyst (Corporate Audi...,2.9,Arrow Electronics\n2.9,"Centennial, CO","Centennial, CO",10000+ employees,1935,Company - Public,Wholesale,Business Services,$10+ billion (USD),"Avnet, Ingram Micro, Tech Data",-1
2250,"Technical Business Analyst (SQL, Data analytic...",$78K-$104K (Glassdoor est.),"Title: Technical Business Analyst (SQL, Data a...",-1.0,Spiceorb,"Denver, CO",-1,-1,-1,-1,-1,-1,-1,-1,-1
2251,"Data Analyst 3, Customer Experience",$78K-$104K (Glassdoor est.),Summary\n\nResponsible for working cross-funct...,3.1,Contingent Network Services\n3.1,"Centennial, CO","West Chester, OH",201 to 500 employees,1984,Company - Private,Enterprise Software & Network Solutions,Information Technology,$25 to $50 million (USD),-1,-1
2252,Senior Quality Data Analyst,$78K-$104K (Glassdoor est.),"You.\n\nYou bring your body, mind, heart and s...",3.4,SCL Health\n3.4,"Broomfield, CO","Broomfield, CO",10000+ employees,1864,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),"Centura Health, HealthONE, Denver Health and H...",-1

In [3]:
numbers = []
for word in df["Salary Estimate"]:
    numbers.append(re.findall(r'\d+', word))


print(numbers)

[['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['37', '66'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['46', '87'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '88'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['51', '87'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['59', '85'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['43', '76'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['60', '110'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['45', '88'], ['45', '88'], ['45', '88'], ['45', '88'], ['45', '88'], ['45', '88'], ['45', '88'], ['45', '88'], ['45', '88'], ['45', '88'], ['45', '88'], ['73', '127'], ['73', '127'], ['73', '127'], ['73', '127'], ['73', '127'], ['73', '127'], ['73', '127'], ['73', '127'], ['73', '127'], ['73', '127'], ['73', '127'], ['73', '127'], ['73', '127'], ['73', '127'], ['84', '90'], ['84', '90'], ['84', '90'], ['84', '90'], ['84', '90'], ['84', '90'], ['84', '90'], ['84', '90'], ['84', '90'], ['84', '90'], ['84', '90'], ['84', '90'], ['84', '90'], ['84', '90'], ['84', '90'], ['84', '90'], ['84', '90'], ['84', '90'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['27', '52'], ['42', '74'], ['42', '74'], ['42', '74'], ['42', '74'], ['42', '74'], ['42', '74'], ['42', '74'], ['42', '74'], ['42', '74'], ['42', '74'], ['42', '74'], ['42', '74'], ['42', '74'], ['42', '74'], ['42', '74'], ['42', '74'], ['42', '74'], ['42', '74'], ['42', '74'], ['42', '74'], ['42', '74'], ['42', '74'], ['42', '74'], ['42', '74'], ['42', '74'], ['42', '74'], ['42', '74'], ['77', '132'], ['77', '132'], ['77', '132'], ['77', '132'], ['77', '132'], ['77', '132'], ['77', '132'], ['77', '132'], ['77', '132'], ['77', '132'], ['77', '132'], ['77', '132'], ['77', '132'], ['77', '132'], ['77', '132'], ['77', '132'], ['77', '132'], ['77', '132'], ['77', '132'], ['77', '132'], ['77', '132'], ['77', '132'], ['77', '132'], ['77', '132'], ['77', '132'], ['77', '132'], ['77', '132'], ['77', '132'], ['77', '132'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['98', '114'], ['48', '96'], ['48', '96'], ['48', '96'], ['48', '96'], ['48', '96'], ['48', '96'], ['48', '96'], ['48', '96'], ['48', '96'], ['48', '96'], ['48', '96'], ['48', '96'], ['48', '96'], ['48', '96'], ['48', '96'], ['48', '96'], ['48', '96'], ['48', '96'], ['48', '96'], ['48', '96'], ['48', '96'], ['48', '96'], ['26', '47'], ['26', '47'], ['26', '47'], ['26', '47'], ['26', '47'], ['26', '47'], ['26', '47'], ['26', '47'], ['26', '47'], ['26', '47'], ['26', '47'], ['26', '47'], ['26', '47'], ['26', '47'], ['26', '47'], ['26', '47'], ['26', '47'], ['26', '47'], ['26', '47'], ['26', '47'], ['26', '47'], ['26', '47'], ['26', '47'], ['26', '47'], ['26', '47'], ['26', '47'], ['26', '47'], ['26', '47'], ['26', '47'], ['31', '59'], ['31', '59'], ['31', '59'], ['31', '59'], ['47', '81'], ['47', '81'], ['47', '81'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['43', '69'], ['49', '112'], ['49', '112'], ['49', '112'], ['49', '112'], ['49', '112'], ['49', '112'], ['49', '112'], ['49', '112'], ['49', '112'], ['49', '112'], ['49', '112'], ['49', '112'], ['49', '112'], ['49', '112'], ['49', '112'], ['49', '112'], ['49', '112'], ['49', '112'], ['30', '54'], ['30', '54'], ['30', '54'], ['30', '54'], ['30', '54'], ['30', '54'], ['30', '54'], ['30', '54'], ['55', '103'], ['55', '103'], ['55', '103'], ['55', '103'], ['55', '103'], ['55', '103'], ['55', '103'], ['55', '103'], ['55', '103'], ['55', '103'], ['55', '103'], ['55', '103'], ['55', '103'], ['55', '103'], ['55', '103'], ['55', '103'], ['55', '103'], ['55', '103'], ['55', '103'], ['55', '103'], ['55', '103'], ['55', '103'], ['55', '103'], ['55', '103'], ['55', '103'], ['55', '103'], ['55', '103'], ['55', '103'], ['55', '103'], ['37', '70'], ['37', '70'], ['37', '70'], ['37', '70'], ['37', '70'], ['37', '70'], ['37', '70'], ['37', '70'], ['37', '70'], ['37', '70'], ['37', '70'], ['37', '70'], ['37', '70'], ['37', '70'], ['37', '70'], ['37', '70'], ['37', '70'], ['37', '70'], ['37', '70'], ['37', '70'], ['37', '70'], ['37', '70'], ['37', '70'], ['37', '70'], ['37', '70'], ['37', '70'], ['37', '70'], ['37', '70'], ['37', '70'], ['57', '103'], ['57', '103'], ['57', '103'], ['57', '103'], ['57', '103'], ['57', '103'], ['57', '103'], ['57', '103'], ['57', '103'], ['57', '103'], ['57', '103'], ['57', '103'], ['57', '103'], ['57', '103'], ['57', '103'], ['57', '103'], ['57', '103'], ['57', '103'], ['57', '103'], ['57', '103'], ['57', '103'], ['57', '103'], ['57', '103'], ['57', '103'], ['57', '103'], ['57', '103'], ['57', '103'], ['57', '103'], ['57', '103'], ['35', '45'], ['35', '45'], ['35', '45'], ['35', '45'], ['35', '45'], ['35', '45'], ['35', '45'], ['35', '45'], ['35', '45'], ['35', '45'], ['35', '45'], ['35', '45'], ['35', '45'], ['35', '45'], ['35', '45'], ['35', '45'], ['35', '45'], ['35', '45'], ['35', '45'], ['35', '45'], ['35', '45'], ['35', '45'], ['35', '45'], ['35', '45'], ['35', '45'], ['35', '45'], ['35', '45'], ['35', '45'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['42', '66'], ['65', '81'], ['65', '81'], ['65', '81'], ['65', '81'], ['65', '81'], ['65', '81'], ['65', '81'], ['65', '81'], ['65', '81'], ['65', '81'], ['65', '81'], ['65', '81'], ['65', '81'], ['65', '81'], ['65', '81'], ['65', '81'], ['65', '81'], ['65', '81'], ['65', '81'], ['65', '81'], ['65', '81'], ['65', '81'], ['65', '81'], ['65', '81'], ['65', '81'], ['65', '81'], ['65', '81'], ['65', '81'], ['65', '81'], ['113', '132'], ['113', '132'], ['113', '132'], ['113', '132'], ['113', '132'], ['113', '132'], ['113', '132'], ['113', '132'], ['113', '132'], ['113', '132'], ['113', '132'], ['113', '132'], ['113', '132'], ['113', '132'], ['113', '132'], ['113', '132'], ['113', '132'], ['113', '132'], ['113', '132'], ['113', '132'], ['113', '132'], ['113', '132'], ['113', '132'], ['113', '132'], ['113', '132'], ['113', '132'], ['113', '132'], ['113', '132'], ['113', '132'], ['42', '63'], ['42', '63'], ['42', '63'], ['42', '63'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['60', '66'], ['73', '82'], ['73', '82'], ['73', '82'], ['73', '82'], ['73', '82'], ['73', '82'], ['73', '82'], ['73', '82'], ['73', '82'], ['73', '82'], ['73', '82'], ['73', '82'], ['73', '82'], ['73', '82'], ['73', '82'], ['73', '82'], ['73', '82'], ['73', '82'], ['73', '82'], ['73', '82'], ['73', '82'], ['73', '82'], ['73', '82'], ['73', '82'], ['73', '82'], ['73', '82'], ['73', '82'], ['73', '82'], ['73', '82'], ['67', '92'], ['67', '92'], ['67', '92'], ['67', '92'], ['67', '92'], ['67', '92'], ['67', '92'], ['67', '92'], ['67', '92'], ['67', '92'], ['67', '92'], ['67', '92'], ['67', '92'], ['67', '92'], ['67', '92'], ['67', '92'], ['67', '92'], ['67', '92'], ['67', '92'], ['67', '92'], ['67', '92'], ['67', '92'], ['67', '92'], ['67', '92'], ['67', '92'], ['67', '92'], ['67', '92'], ['67', '92'], ['67', '92'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['42', '76'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['97', '129'], ['68', '87'], ['68', '87'], ['68', '87'], ['68', '87'], ['68', '87'], ['68', '87'], ['68', '87'], ['68', '87'], ['68', '87'], ['68', '87'], ['68', '87'], ['68', '87'], ['68', '87'], ['68', '87'], ['68', '87'], ['68', '87'], ['29', '38'], ['29', '38'], ['29', '38'], ['29', '38'], ['29', '38'], ['29', '38'], ['29', '38'], ['29', '38'], ['29', '38'], ['29', '38'], ['29', '38'], ['29', '38'], ['29', '38'], ['29', '38'], ['29', '38'], ['29', '38'], ['29', '38'], ['29', '38'], ['29', '38'], ['29', '38'], ['29', '38'], ['29', '38'], ['29', '38'], ['29', '38'], ['29', '38'], ['29', '38'], ['29', '38'], ['29', '38'], ['29', '38'], ['47', '76'], ['47', '76'], ['47', '76'], ['47', '76'], ['47', '76'], ['47', '76'], ['47', '76'], ['47', '76'], ['47', '76'], ['47', '76'], ['47', '76'], ['47', '76'], ['47', '76'], ['47', '76'], ['47', '76'], ['47', '76'], ['47', '76'], ['47', '76'], ['47', '76'], ['47', '76'], ['47', '76'], ['47', '76'], ['47', '76'], ['47', '76'], ['47', '76'], ['47', '76'], ['47', '76'], ['47', '76'], ['74', '123'], ['74', '123'], ['74', '123'], ['74', '123'], ['74', '123'], ['74', '123'], ['74', '123'], ['74', '123'], ['74', '123'], ['74', '123'], ['74', '123'], ['74', '123'], ['74', '123'], ['74', '123'], ['74', '123'], ['74', '123'], ['74', '123'], ['74', '123'], ['74', '123'], ['74', '123'], ['74', '123'], ['74', '123'], ['74', '123'], ['74', '123'], ['74', '123'], ['74', '123'], ['74', '123'], ['74', '123'], ['53', '94'], ['53', '94'], ['53', '94'], ['53', '94'], ['53', '94'], ['53', '94'], ['53', '94'], ['53', '94'], ['53', '94'], ['53', '94'], ['53', '94'], ['53', '94'], ['53', '94'], ['53', '94'], ['53', '94'], ['53', '94'], ['53', '94'], ['53', '94'], ['53', '94'], ['53', '94'], ['53', '94'], ['53', '94'], ['53', '94'], ['53', '94'], ['53', '94'], ['53', '94'], ['53', '94'], ['53', '94'], ['53', '94'], ['46', '102'], ['46', '102'], ['46', '102'], ['46', '102'], ['46', '102'], ['46', '102'], ['46', '102'], ['46', '102'], ['46', '102'], ['46', '102'], ['46', '102'], ['46', '102'], ['46', '102'], ['46', '102'], ['46', '102'], ['46', '102'], ['46', '102'], ['46', '102'], ['46', '102'], ['46', '102'], ['46', '102'], ['46', '102'], ['46', '102'], ['46', '102'], ['46', '102'], ['46', '102'], ['46', '102'], ['46', '102'], ['43', '94'], ['43', '94'], ['43', '94'], ['43', '94'], ['43', '94'], ['43', '94'], ['43', '94'], ['43', '94'], ['43', '94'], ['43', '94'], ['43', '94'], ['43', '94'], ['43', '94'], ['43', '94'], ['43', '94'], ['43', '94'], ['43', '94'], ['43', '94'], ['43', '94'], ['43', '94'], ['43', '94'], ['43', '94'], ['43', '94'], ['43', '94'], ['43', '94'], ['43', '94'], ['43', '94'], ['43', '94'], ['43', '94'], ['45', '78'], ['45', '78'], ['45', '78'], ['45', '78'], ['45', '78'], ['45', '78'], ['45', '78'], ['45', '78'], ['45', '78'], ['45', '78'], ['45', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['41', '78'], ['38', '68'], ['38', '68'], ['38', '68'], ['38', '68'], ['38', '68'], ['38', '68'], ['38', '68'], ['38', '68'], ['38', '68'], ['38', '68'], ['38', '68'], ['38', '68'], ['38', '68'], ['38', '68'], ['38', '68'], ['38', '68'], ['38', '68'], ['38', '68'], ['38', '68'], ['38', '68'], ['38', '68'], ['38', '68'], ['38', '68'], ['38', '68'], ['38', '68'], ['38', '68'], ['38', '68'], ['38', '68'], ['38', '68'], ['37', '44'], ['37', '44'], ['37', '44'], ['37', '44'], ['37', '44'], ['37', '44'], ['37', '44'], ['37', '44'], ['37', '44'], ['37', '44'], ['37', '44'], ['37', '44'], ['37', '44'], ['37', '44'], ['37', '44'], ['37', '44'], ['37', '44'], ['37', '44'], ['37', '44'], ['37', '44'], ['37', '44'], ['37', '44'], ['37', '44'], ['37', '44'], ['37', '44'], ['37', '44'], ['37', '44'], ['37', '44'], ['37', '44'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['64', '113'], ['50', '93'], ['50', '93'], ['50', '93'], ['50', '93'], ['50', '93'], ['50', '93'], ['50', '93'], ['50', '93'], ['50', '93'], ['50', '93'], ['50', '93'], ['50', '93'], ['50', '93'], ['50', '93'], ['50', '93'], ['50', '93'], ['50', '93'], ['50', '93'], ['50', '93'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['37', '68'], ['73', '89'], ['73', '89'], ['73', '89'], ['73', '89'], ['73', '89'], ['73', '89'], ['73', '89'], ['73', '89'], ['73', '89'], ['73', '89'], ['73', '89'], ['73', '89'], ['73', '89'], ['73', '89'], ['73', '89'], ['73', '89'], ['73', '89'], ['73', '89'], ['76', '122'], ['76', '122'], ['76', '122'], ['76', '122'], ['76', '122'], ['76', '122'], ['76', '122'], ['76', '122'], ['76', '122'], ['76', '122'], ['76', '122'], ['76', '122'], ['76', '122'], ['76', '122'], ['76', '122'], ['76', '122'], ['76', '122'], ['76', '122'], ['76', '122'], ['76', '122'], ['76', '122'], ['76', '122'], ['76', '122'], ['76', '122'], ['76', '122'], ['76', '122'], ['76', '122'], ['76', '122'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['60', '124'], ['34', '61'], ['34', '61'], ['34', '61'], ['34', '61'], ['34', '61'], ['24', '48'], ['24', '48'], ['24', '48'], ['24', '48'], ['24', '48'], ['24', '48'], ['24', '48'], ['24', '48'], ['24', '48'], ['24', '48'], ['24', '48'], ['24', '48'], ['24', '48'], ['24', '48'], ['24', '48'], ['24', '48'], ['24', '48'], ['24', '48'], ['24', '48'], ['24', '48'], ['24', '48'], ['24', '48'], ['24', '48'], ['24', '48'], ['24', '48'], ['24', '48'], ['24', '48'], ['24', '48'], ['24', '48'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['30', '53'], ['41', '86'], ['41', '86'], ['41', '86'], ['41', '86'], ['41', '86'], ['41', '86'], ['41', '86'], ['41', '86'], ['41', '86'], ['41', '86'], ['41', '86'], ['41', '86'], ['41', '86'], ['41', '86'], ['41', '86'], ['41', '86'], ['41', '86'], ['41', '86'], ['41', '86'], ['41', '86'], ['41', '86'], ['41', '86'], ['41', '86'], ['41', '86'], ['41', '86'], ['41', '86'], ['41', '86'], [

In [4]:
high = []
low = []
index = 0
for listy in numbers:
    low.append(int(listy[0])* 1000)
    try:
        high.append(int(listy[1])*1000)
    except IndexError:
        high.append("null")
    index += 1
print(high)
print(low)

[66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 85000, 85000, 85000, 85000, 85000, 85000, 85000, 85000, 85000, 85000, 85000, 85000, 85000, 85000, 85000, 85000, 85000, 85000, 85000, 85000, 85000, 85000, 85000, 85000, 85000, 85000, 85000, 85000, 85000, 85000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000, 110000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 90000, 90000, 90000, 90000, 90000, 90000, 90000, 90000, 90000, 90000, 90000, 90000, 90000, 90000, 90000, 90000, 90000, 90000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 114000, 114000, 114000, 114000, 114000, 114000, 114000, 114000, 114000, 114000, 114000, 114000, 114000, 114000, 114000, 114000, 114000, 114000, 114000, 114000, 114000, 114000, 114000, 114000, 114000, 114000, 114000, 114000, 114000, 114000, 96000, 96000, 96000, 96000, 96000, 96000, 96000, 96000, 96000, 96000, 96000, 96000, 96000, 96000, 96000, 96000, 96000, 96000, 96000, 96000, 96000, 96000, 47000, 47000, 47000, 47000, 47000, 47000, 47000, 47000, 47000, 47000, 47000, 47000, 47000, 47000, 47000, 47000, 47000, 47000, 47000, 47000, 47000, 47000, 47000, 47000, 47000, 47000, 47000, 47000, 47000, 59000, 59000, 59000, 59000, 81000, 81000, 81000, 69000, 69000, 69000, 69000, 69000, 69000, 69000, 69000, 69000, 69000, 69000, 69000, 69000, 69000, 69000, 69000, 69000, 69000, 69000, 69000, 69000, 69000, 69000, 69000, 69000, 69000, 69000, 69000, 69000, 69000, 112000, 112000, 112000, 112000, 112000, 112000, 112000, 112000, 112000, 112000, 112000, 112000, 112000, 112000, 112000, 112000, 112000, 112000, 54000, 54000, 54000, 54000, 54000, 54000, 54000, 54000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 70000, 70000, 70000, 70000, 70000, 70000, 70000, 70000, 70000, 70000, 70000, 70000, 70000, 70000, 70000, 70000, 70000, 70000, 70000, 70000, 70000, 70000, 70000, 70000, 70000, 70000, 70000, 70000, 70000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 103000, 45000, 45000, 45000, 45000, 45000, 45000, 45000, 45000, 45000, 45000, 45000, 45000, 45000, 45000, 45000, 45000, 45000, 45000, 45000, 45000, 45000, 45000, 45000, 45000, 45000, 45000, 45000, 45000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 81000, 81000, 81000, 81000, 81000, 81000, 81000, 81000, 81000, 81000, 81000, 81000, 81000, 81000, 81000, 81000, 81000, 81000, 81000, 81000, 81000, 81000, 81000, 81000, 81000, 81000, 81000, 81000, 81000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 132000, 63000, 63000, 63000, 63000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 66000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 129000, 129000, 129000, 129000, 129000, 129000, 129000, 129000, 129000, 129000, 129000, 129000, 129000, 129000, 129000, 129000, 129000, 129000, 129000, 129000, 129000, 129000, 129000, 129000, 129000, 129000, 129000, 129000, 129000, 129000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 87000, 38000, 38000, 38000, 38000, 38000, 38000, 38000, 38000, 38000, 38000, 38000, 38000, 38000, 38000, 38000, 38000, 38000, 38000, 38000, 38000, 38000, 38000, 38000, 38000, 38000, 38000, 38000, 38000, 38000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 123000, 123000, 123000, 123000, 123000, 123000, 123000, 123000, 123000, 123000, 123000, 123000, 123000, 123000, 123000, 123000, 123000, 123000, 123000, 123000, 123000, 123000, 123000, 123000, 123000, 123000, 123000, 123000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 102000, 102000, 102000, 102000, 102000, 102000, 102000, 102000, 102000, 102000, 102000, 102000, 102000, 102000, 102000, 102000, 102000, 102000, 102000, 102000, 102000, 102000, 102000, 102000, 102000, 102000, 102000, 102000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 94000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 44000, 44000, 44000, 44000, 44000, 44000, 44000, 44000, 44000, 44000, 44000, 44000, 44000, 44000, 44000, 44000, 44000, 44000, 44000, 44000, 44000, 44000, 44000, 44000, 44000, 44000, 44000, 44000, 44000, 113000, 113000, 113000, 113000, 113000, 113000, 113000, 113000, 113000, 113000, 113000, 113000, 113000, 113000, 113000, 113000, 113000, 113000, 113000, 113000, 113000, 113000, 113000, 113000, 113000, 113000, 113000, 113000, 113000, 113000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 68000, 89000, 89000, 89000, 89000, 89000, 89000, 89000, 89000, 89000, 89000, 89000, 89000, 89000, 89000, 89000, 89000, 89000, 89000, 122000, 122000, 122000, 122000, 122000, 122000, 122000, 122000, 122000, 122000, 122000, 122000, 122000, 122000, 122000, 122000, 122000, 122000, 122000, 122000, 122000, 122000, 122000, 122000, 122000, 122000, 122000, 122000, 124000, 124000, 124000, 124000, 124000, 124000, 124000, 124000, 124000, 124000, 124000, 124000, 124000, 124000, 124000, 124000, 124000, 124000, 124000, 124000, 124000, 124000, 124000, 124000, 124000, 124000, 124000, 124000, 124000, 124000, 124000, 61000, 61000, 61000, 61000, 61000, 48000, 48000, 48000, 48000, 48000, 48000, 48000, 48000, 48000, 48000, 48000, 48000, 48000, 48000, 48000, 48000, 48000, 48000, 48000, 48000, 48000, 48000, 48000, 48000, 48000, 48000, 48000, 48000, 48000, 53000, 53000, 53000, 53000, 53000, 53000, 53000, 53000, 53000, 53000, 53000, 53000, 53000, 53000, 53000, 53000, 53000, 53000, 53000, 53000, 53000, 53000, 53000, 53000, 53000, 53000, 53000, 53000, 53000, 53000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 82000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 88000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 78000, 190000, 190000, 190000, 190000, 190000, 190000, 190000, 190000, 190000, 190000, 190000, 190000, 190000, 190000, 190000, 190000, 190000, 190000, 190000, 190000, 190000, 190000, 190000, 190000, 190000, 190000, 190000, 190000, 190000, 151000, 151000, 151000, 151000, 151000, 151000, 151000, 151000, 151000, 151000, 151000, 151000, 151000, 151000, 151000, 151000, 151000, 151000, 151000, 151000, 151000, 151000, 151000, 151000, 151000, 151000, 151000, 151000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 127000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 93000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 76000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 42000, 42000, 42000, 42000, 42000, 42000, 42000, 42000, 42000, 42000, 42000, 42000, 42000, 42000, 42000, 42000, 42000, 42000, 42000, 42000, 42000, 42000, 42000, 42000, 42000, 42000, 42000, 42000, 42000, 42000, 77000, 77000, 77000, 72000, 72000, 72000, 72000, 72000, 72000, 72000, 72000, 72000, 72000, 72000, 72000, 72000, 72000, 72000, 72000, 72000, 72000, 72000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 70000, 70000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 52000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 75000, 75000, 75000, 75000, 75000, 75000, 75000, 75000, 75000, 75000, 75000, 75000, 75000, 75000, 75000, 75000, 75000, 75000, 75000, 75000, 75000, 75000, 75000, 75000, 75000, 75000, 75000, 75000, 99000, 99000, 99000, 99000, 99000, 99000, 99000, 99000, 99000, 99000, 99000, 99000, 99000, 99000, 99000, 99000, 99000, 99000, 99000, 99000, 99000, 99000, 99000, 99000, 99000, 99000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 178000, 178000, 178000, 178000, 178000, 178000, 178000, 178000, 178000, 178000, 178000, 178000, 178000, 178000, 178000, 178000, 178000, 178000, 178000, 178000, 178000, 178000, 178000, 178000, 178000, 178000, 178000, 178000, 159000, 159000, 159000, 159000, 159000, 159000, 159000, 159000, 159000, 159000, 159000, 159000, 159000, 159000, 159000, 159000, 159000, 159000, 159000, 159000, 159000, 159000, 159000, 159000, 159000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 116000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 86000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 74000, 61000, 61000, 61000, 61000, 61000, 61000, 61000, 61000, 61000, 61000, 61000, 61000, 61000, 61000, 61000, 61000, 61000, 61000, 61000, 61000, 61000, 61000, 61000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 101000, 101000, 101000, 101000, 101000, 101000, 101000, 101000, 101000, 101000, 101000, 101000, 101000, 101000, 101000, 101000, 101000, 101000, 101000, 101000, 101000, 101000, 101000, 101000, 101000, 101000, 101000, 'null', 56000, 56000, 56000, 56000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000, 104000]

In [5]:
df["Salary Low"] = low
df["Salary High"] = high
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply,Salary Low,Salary High
0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True,37000,66000
1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1,37000,66000
2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1,37000,66000
3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1,37000,66000
4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True,37000,66000

In [6]:
df.loc[df["Salary High"] == "null", :]

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply,Salary Low,Salary High
2149,Configuration/Data Management Analyst III,-1,Job Description\nPosition Title: Configuration...,4.4,Protingent\n4.4,"Kent, WA","Bellevue, WA",51 to 200 employees,2001,Company - Private,Staffing & Outsourcing,Business Services,$25 to $50 million (USD),-1,-1,1000,null

In [7]:
df = df.loc[df["Salary High"] != "null", :]
df

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply,Salary Low,Salary High
0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True,37000,66000
1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1,37000,66000
2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1,37000,66000
3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1,37000,66000
4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True,37000,66000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2248,RQS - IHHA - 201900004460 -1q Data Security An...,$78K-$104K (Glassdoor est.),Maintains systems to protect data from unautho...,2.5,"Avacend, Inc.\n2.5","Denver, CO","Alpharetta, GA",51 to 200 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,Unknown / Non-Applicable,-1,-1,78000,104000
2249,Senior Data Analyst (Corporate Audit),$78K-$104K (Glassdoor est.),Position:\nSenior Data Analyst (Corporate Audi...,2.9,Arrow Electronics\n2.9,"Centennial, CO","Centennial, CO",10000+ employees,1935,Company - Public,Wholesale,Business Services,$10+ billion (USD),"Avnet, Ingram Micro, Tech Data",-1,78000,104000
2250,"Technical Business Analyst (SQL, Data analytic...",$78K-$104K (Glassdoor est.),"Title: Technical Business Analyst (SQL, Data a...",-1.0,Spiceorb,"Denver, CO",-1,-1,-1,-1,-1,-1,-1,-1,-1,78000,104000
2251,"Data Analyst 3, Customer Experience",$78K-$104K (Glassdoor est.),Summary\n\nResponsible for working cross-funct...,3.1,Contingent Network Services\n3.1,"Centennial, CO","West Chester, OH",201 to 500 employees,1984,Company - Private,Enterprise Software & Network Solutions,Information Technology,$25 to $50 million (USD),-1,-1,78000,104000
2252,Senior Quality Data Analyst,$78K-$104K (Glassdoor est.),"You.\n\nYou bring your body, mind, heart and s...",3.4,SCL Health\n3.4,"Broomfield, CO","Broomfield, CO",10000+ employees,1864,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),"Centura Health, HealthONE, Denver Health and H...",-1,78000,104000

In [8]:
df["Size"].value_counts()

51 to 200 employees        420
10000+ employees           375
1001 to 5000 employees     348
1 to 50 employees          347
201 to 500 employees       249
501 to 1000 employees      211
-1                         163
5001 to 10000 employees     97
Unknown                     42
Name: Size, dtype: int64

In [9]:
df['Size'] = df['Size'].str.replace('-1', 'Unknown')

/Users/lucykaplan/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [10]:
df['Industry'] = df['Industry'].str.replace('-1', 'Other')

/Users/lucykaplan/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [11]:
df['Company Name'] = df['Company Name'].str.replace('\\n', '')

/Users/lucykaplan/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [12]:
df['Company Name'] = df['Company Name'].str.replace('.', '')

/Users/lucykaplan/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [13]:
df['Company Name'] = df['Company Name'].str.replace('\d+', '')
df

/Users/lucykaplan/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply,Salary Low,Salary High
0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True,37000,66000
1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1,37000,66000
2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1,37000,66000
3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1,37000,66000
4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True,37000,66000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2248,RQS - IHHA - 201900004460 -1q Data Security An...,$78K-$104K (Glassdoor est.),Maintains systems to protect data from unautho...,2.5,"Avacend, Inc","Denver, CO","Alpharetta, GA",51 to 200 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,Unknown / Non-Applicable,-1,-1,78000,104000
2249,Senior Data Analyst (Corporate Audit),$78K-$104K (Glassdoor est.),Position:\nSenior Data Analyst (Corporate Audi...,2.9,Arrow Electronics,"Centennial, CO","Centennial, CO",10000+ employees,1935,Company - Public,Wholesale,Business Services,$10+ billion (USD),"Avnet, Ingram Micro, Tech Data",-1,78000,104000
2250,"Technical Business Analyst (SQL, Data analytic...",$78K-$104K (Glassdoor est.),"Title: Technical Business Analyst (SQL, Data a...",-1.0,Spiceorb,"Denver, CO",-1,Unknown,-1,-1,Other,-1,-1,-1,-1,78000,104000
2251,"Data Analyst 3, Customer Experience",$78K-$104K (Glassdoor est.),Summary\n\nResponsible for working cross-funct...,3.1,Contingent Network Services,"Centennial, CO","West Chester, OH",201 to 500 employees,1984,Company - Private,Enterprise Software & Network Solutions,Information Technology,$25 to $50 million (USD),-1,-1,78000,104000
2252,Senior Quality Data Analyst,$78K-$104K (Glassdoor est.),"You.\n\nYou bring your body, mind, heart and s...",3.4,SCL Health,"Broomfield, CO","Broomfield, CO",10000+ employees,1864,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),"Centura Health, HealthONE, Denver Health and H...",-1,78000,104000

In [19]:
df['Rating'] = df['Rating'].replace(-1.0, 'Unknown')
df

<ipython-input-19-d982246366ae>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Rating'] = df['Rating'].replace(-1.0, 'Unknown')

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply,Salary Low,Salary High
0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,201 to 500 employees,Non-Profit,$100 to $500 million (USD),-1,True,37000,66000
1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,10000+ employees,Health Care,$2 to $5 billion (USD),-1,-1,37000,66000
2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,1001 to 5000 employees,Information Technology,Unknown / Non-Applicable,GoDaddy,-1,37000,66000
3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,201 to 500 employees,Information Technology,$50 to $100 million (USD),-1,-1,37000,66000
4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,501 to 1000 employees,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True,37000,66000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2248,RQS - IHHA - 201900004460 -1q Data Security An...,$78K-$104K (Glassdoor est.),Maintains systems to protect data from unautho...,2.5,"Avacend, Inc","Denver, CO","Alpharetta, GA",51 to 200 employees,-1,Company - Private,51 to 200 employees,Business Services,Unknown / Non-Applicable,-1,-1,78000,104000
2249,Senior Data Analyst (Corporate Audit),$78K-$104K (Glassdoor est.),Position:\nSenior Data Analyst (Corporate Audi...,2.9,Arrow Electronics,"Centennial, CO","Centennial, CO",10000+ employees,1935,Company - Public,10000+ employees,Business Services,$10+ billion (USD),"Avnet, Ingram Micro, Tech Data",-1,78000,104000
2250,"Technical Business Analyst (SQL, Data analytic...",$78K-$104K (Glassdoor est.),"Title: Technical Business Analyst (SQL, Data a...",Unknown,Spiceorb,"Denver, CO",-1,Unknown,-1,-1,Unknown,-1,-1,-1,-1,78000,104000
2251,"Data Analyst 3, Customer Experience",$78K-$104K (Glassdoor est.),Summary\n\nResponsible for working cross-funct...,3.1,Contingent Network Services,"Centennial, CO","West Chester, OH",201 to 500 employees,1984,Company - Private,201 to 500 employees,Information Technology,$25 to $50 million (USD),-1,-1,78000,104000
2252,Senior Quality Data Analyst,$78K-$104K (Glassdoor est.),"You.\n\nYou bring your body, mind, heart and s...",3.4,SCL Health,"Broomfield, CO","Broomfield, CO",10000+ employees,1864,Nonprofit Organization,10000+ employees,Health Care,$2 to $5 billion (USD),"Centura Health, HealthONE, Denver Health and H...",-1,78000,104000

In [20]:
df['Headquarters'] = df['Headquarters'].str.replace('-1', 'Unknown')

<ipython-input-20-9af6dabf0628>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Headquarters'] = df['Headquarters'].str.replace('-1', 'Unknown')

In [25]:
df['Founded'] = df['Founded'].replace(-1, 'Unknown')

<ipython-input-25-3152c67c884a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Founded'] = df['Founded'].replace(-1, 'Unknown')

In [23]:
df['Type of ownership'] = df['Type of ownership'].str.replace('-1', 'Unknown')

<ipython-input-23-aa733d2b160e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Type of ownership'] = df['Type of ownership'].str.replace('-1', 'Unknown')

In [26]:
df['Sector'] = df['Sector'].str.replace('-1', 'Unknown')
df

<ipython-input-26-23d587b62b23>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sector'] = df['Sector'].str.replace('-1', 'Unknown')

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply,Salary Low,Salary High
0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,201 to 500 employees,Non-Profit,$100 to $500 million (USD),-1,True,37000,66000
1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,10000+ employees,Health Care,$2 to $5 billion (USD),-1,-1,37000,66000
2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,1001 to 5000 employees,Information Technology,Unknown / Non-Applicable,GoDaddy,-1,37000,66000
3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,201 to 500 employees,Information Technology,$50 to $100 million (USD),-1,-1,37000,66000
4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,501 to 1000 employees,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True,37000,66000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2248,RQS - IHHA - 201900004460 -1q Data Security An...,$78K-$104K (Glassdoor est.),Maintains systems to protect data from unautho...,2.5,"Avacend, Inc","Denver, CO","Alpharetta, GA",51 to 200 employees,Unknown,Company - Private,51 to 200 employees,Business Services,Unknown / Non-Applicable,-1,-1,78000,104000
2249,Senior Data Analyst (Corporate Audit),$78K-$104K (Glassdoor est.),Position:\nSenior Data Analyst (Corporate Audi...,2.9,Arrow Electronics,"Centennial, CO","Centennial, CO",10000+ employees,1935,Company - Public,10000+ employees,Business Services,$10+ billion (USD),"Avnet, Ingram Micro, Tech Data",-1,78000,104000
2250,"Technical Business Analyst (SQL, Data analytic...",$78K-$104K (Glassdoor est.),"Title: Technical Business Analyst (SQL, Data a...",Unknown,Spiceorb,"Denver, CO",Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,-1,-1,-1,78000,104000
2251,"Data Analyst 3, Customer Experience",$78K-$104K (Glassdoor est.),Summary\n\nResponsible for working cross-funct...,3.1,Contingent Network Services,"Centennial, CO","West Chester, OH",201 to 500 employees,1984,Company - Private,201 to 500 employees,Information Technology,$25 to $50 million (USD),-1,-1,78000,104000
2252,Senior Quality Data Analyst,$78K-$104K (Glassdoor est.),"You.\n\nYou bring your body, mind, heart and s...",3.4,SCL Health,"Broomfield, CO","Broomfield, CO",10000+ employees,1864,Nonprofit Organization,10000+ employees,Health Care,$2 to $5 billion (USD),"Centura Health, HealthONE, Denver Health and H...",-1,78000,104000

In [27]:
df.to_csv("data/CleanDataAnalyst.csv", index = False)